export const images = {
  slushLogo: require('../../assets/images/slushLogo.png'),
  backArrow: require('../../assets/images/backArrow.png'),
  mail: require('../../assets/images/mail.png'),
  lock: require('../../assets/images/lock.png'),
  facebook: require('../../assets/images/facebook.png'),
  apple: require('../../assets/images/apple.png'),
  google: require('../../assets/images/google.png'),
  profileImage: require('../../assets/images/profileImage.png'),
  female: require('../../assets/images/female.png'),
  male: require('../../assets/images/male.png'),
  inter: require('../../assets/images/inter.png'),
  location: require('../../assets/images/location.png'),
  location_black: require('../../assets/images/location-black.png'),
  myEventsImage1: require('../../assets/images/myEventsImage1.jpeg'),
  eventImage1: require('../../assets/images/eventImage1.jpeg'),
  eventImage2: require('../../assets/images/eventImage2.jpeg'),
  clock: require('../../assets/images/clock.png'),
  calender: require('../../assets/images/calender.png'),
  ticketHeaderImage: require('../../assets/images/ticketHeaderImage.png'),
  ticketBookedImage: require('../../assets/images/ticketBookedImage.png'),
};
